// default package
// Generated Feb 3, 2015 3:11:58 PM by Hibernate Tools 4.0.0
package com.itu.bean;
import java.util.Date;

/**
 * CloudCommand generated by hbm2java
 */
public class CloudCommand implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private Integer commandId;
	private String name;
	private Integer dataLength;
	private Integer checked;
	private Integer coordinatorId;
	private Integer smartmeterId;
	private Integer param1;

	public CloudCommand() {
	}

	public CloudCommand(Integer commandId, String name, Integer dataLength,
			Integer checked, Integer coordinatorId, Integer smartmeterId,
			Integer param1) {
		this.commandId = commandId;
		this.name = name;
		this.dataLength = dataLength;
		this.checked = checked;
		this.coordinatorId = coordinatorId;
		this.smartmeterId = smartmeterId;
		this.param1 = param1;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public Integer getCommandId() {
		return this.commandId;
	}

	public void setCommandId(Integer commandId) {
		this.commandId = commandId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getDataLength() {
		return this.dataLength;
	}

	public void setDataLength(Integer dataLength) {
		this.dataLength = dataLength;
	}

	public Integer getChecked() {
		return this.checked;
	}

	public void setChecked(Integer checked) {
		this.checked = checked;
	}

	public Integer getCoordinatorId() {
		return this.coordinatorId;
	}

	public void setCoordinatorId(Integer coordinatorId) {
		this.coordinatorId = coordinatorId;
	}

	public Integer getSmartmeterId() {
		return this.smartmeterId;
	}

	public void setSmartmeterId(Integer smartmeterId) {
		this.smartmeterId = smartmeterId;
	}

	public Integer getParam1() {
		return this.param1;
	}

	public void setParam1(Integer param1) {
		this.param1 = param1;
	}

}
