// default package
// Generated Feb 2, 2015 11:46:22 AM by Hibernate Tools 4.0.0
package com.itu.bean;
import java.util.Date;

/**
 * CommandLog generated by hbm2java
 */
public class CommandLog implements java.io.Serializable {

	private Integer id;
	private Command command;
	private String commandStream;
	private String commandResult;
	private String commandData;
	private String commandStatus;
	private String generatedBy;
	private Date generatedTime;
	private Date executedTime;
	private String lsdbInsertedTime;

	public CommandLog() {
	}

	public CommandLog(Command command, String commandStream,
			String commandResult, String commandData, String commandStatus,
			String generatedBy, Date generatedTime, Date executedTime,
			String lsdbInsertedTime) {
		this.command = command;
		this.commandStream = commandStream;
		this.commandResult = commandResult;
		this.commandData = commandData;
		this.commandStatus = commandStatus;
		this.generatedBy = generatedBy;
		this.generatedTime = generatedTime;
		this.executedTime = executedTime;
		this.lsdbInsertedTime = lsdbInsertedTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Command getCommand() {
		return this.command;
	}

	public void setCommand(Command command) {
		this.command = command;
	}

	public String getCommandStream() {
		return this.commandStream;
	}

	public void setCommandStream(String commandStream) {
		this.commandStream = commandStream;
	}

	public String getCommandResult() {
		return this.commandResult;
	}

	public void setCommandResult(String commandResult) {
		this.commandResult = commandResult;
	}

	public String getCommandData() {
		return this.commandData;
	}

	public void setCommandData(String commandData) {
		this.commandData = commandData;
	}

	public String getCommandStatus() {
		return this.commandStatus;
	}

	public void setCommandStatus(String commandStatus) {
		this.commandStatus = commandStatus;
	}

	public String getGeneratedBy() {
		return this.generatedBy;
	}

	public void setGeneratedBy(String generatedBy) {
		this.generatedBy = generatedBy;
	}

	public Date getGeneratedTime() {
		return this.generatedTime;
	}

	public void setGeneratedTime(Date generatedTime) {
		this.generatedTime = generatedTime;
	}

	public Date getExecutedTime() {
		return this.executedTime;
	}

	public void setExecutedTime(Date executedTime) {
		this.executedTime = executedTime;
	}

	public String getLsdbInsertedTime() {
		return this.lsdbInsertedTime;
	}

	public void setLsdbInsertedTime(String lsdbInsertedTime) {
		this.lsdbInsertedTime = lsdbInsertedTime;
	}

}
