// default package
// Generated Feb 2, 2015 11:46:22 AM by Hibernate Tools 4.0.0
package com.itu.bean;
/**
 * ParameterRegister generated by hbm2java
 */
public class ParameterRegister implements java.io.Serializable {

	private Integer id;
	private Integer coordinatorId;
	private Integer minAdc;
	private Integer maxAdc;
	private Integer sampleInt;
	private Integer sampleWin;
	private Integer magV1;
	private Integer magI1;
	private Integer magV2;
	private Integer magI2;
	private Integer magV3;
	private Integer magI3;
	private Integer minV;
	private Integer maxV;
	private Integer minI;
	private Integer maxI;
	private Integer TEff;
	private Integer sharp;
	private Integer peak;
	private Integer shoulder;
	private Integer off;
	private Integer NSm;

	public ParameterRegister() {
	}

	public ParameterRegister(Integer coordinatorId, Integer minAdc,
			Integer maxAdc, Integer sampleInt, Integer sampleWin,
			Integer magV1, Integer magI1, Integer magV2, Integer magI2,
			Integer magV3, Integer magI3, Integer minV, Integer maxV,
			Integer minI, Integer maxI, Integer TEff, Integer sharp,
			Integer peak, Integer shoulder, Integer off, Integer NSm) {
		this.coordinatorId = coordinatorId;
		this.minAdc = minAdc;
		this.maxAdc = maxAdc;
		this.sampleInt = sampleInt;
		this.sampleWin = sampleWin;
		this.magV1 = magV1;
		this.magI1 = magI1;
		this.magV2 = magV2;
		this.magI2 = magI2;
		this.magV3 = magV3;
		this.magI3 = magI3;
		this.minV = minV;
		this.maxV = maxV;
		this.minI = minI;
		this.maxI = maxI;
		this.TEff = TEff;
		this.sharp = sharp;
		this.peak = peak;
		this.shoulder = shoulder;
		this.off = off;
		this.NSm = NSm;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCoordinatorId() {
		return this.coordinatorId;
	}

	public void setCoordinatorId(Integer coordinatorId) {
		this.coordinatorId = coordinatorId;
	}

	public Integer getMinAdc() {
		return this.minAdc;
	}

	public void setMinAdc(Integer minAdc) {
		this.minAdc = minAdc;
	}

	public Integer getMaxAdc() {
		return this.maxAdc;
	}

	public void setMaxAdc(Integer maxAdc) {
		this.maxAdc = maxAdc;
	}

	public Integer getSampleInt() {
		return this.sampleInt;
	}

	public void setSampleInt(Integer sampleInt) {
		this.sampleInt = sampleInt;
	}

	public Integer getSampleWin() {
		return this.sampleWin;
	}

	public void setSampleWin(Integer sampleWin) {
		this.sampleWin = sampleWin;
	}

	public Integer getMagV1() {
		return this.magV1;
	}

	public void setMagV1(Integer magV1) {
		this.magV1 = magV1;
	}

	public Integer getMagI1() {
		return this.magI1;
	}

	public void setMagI1(Integer magI1) {
		this.magI1 = magI1;
	}

	public Integer getMagV2() {
		return this.magV2;
	}

	public void setMagV2(Integer magV2) {
		this.magV2 = magV2;
	}

	public Integer getMagI2() {
		return this.magI2;
	}

	public void setMagI2(Integer magI2) {
		this.magI2 = magI2;
	}

	public Integer getMagV3() {
		return this.magV3;
	}

	public void setMagV3(Integer magV3) {
		this.magV3 = magV3;
	}

	public Integer getMagI3() {
		return this.magI3;
	}

	public void setMagI3(Integer magI3) {
		this.magI3 = magI3;
	}

	public Integer getMinV() {
		return this.minV;
	}

	public void setMinV(Integer minV) {
		this.minV = minV;
	}

	public Integer getMaxV() {
		return this.maxV;
	}

	public void setMaxV(Integer maxV) {
		this.maxV = maxV;
	}

	public Integer getMinI() {
		return this.minI;
	}

	public void setMinI(Integer minI) {
		this.minI = minI;
	}

	public Integer getMaxI() {
		return this.maxI;
	}

	public void setMaxI(Integer maxI) {
		this.maxI = maxI;
	}

	public Integer getTEff() {
		return this.TEff;
	}

	public void setTEff(Integer TEff) {
		this.TEff = TEff;
	}

	public Integer getSharp() {
		return this.sharp;
	}

	public void setSharp(Integer sharp) {
		this.sharp = sharp;
	}

	public Integer getPeak() {
		return this.peak;
	}

	public void setPeak(Integer peak) {
		this.peak = peak;
	}

	public Integer getShoulder() {
		return this.shoulder;
	}

	public void setShoulder(Integer shoulder) {
		this.shoulder = shoulder;
	}

	public Integer getOff() {
		return this.off;
	}

	public void setOff(Integer off) {
		this.off = off;
	}

	public Integer getNSm() {
		return this.NSm;
	}

	public void setNSm(Integer NSm) {
		this.NSm = NSm;
	}

}
