// default package
// Generated Feb 3, 2015 12:02:04 PM by Hibernate Tools 4.0.0

/**
 * SmartMeter generated by hbm2java
 */
public class SmartMeter implements java.io.Serializable {

	private int id;
	private Integer coordinatorId;
	private String ieeeAddress;
	private Integer validation;

	public SmartMeter() {
	}

	public SmartMeter(int id) {
		this.id = id;
	}

	public SmartMeter(int id, Integer coordinatorId, String ieeeAddress,
			Integer validation) {
		this.id = id;
		this.coordinatorId = coordinatorId;
		this.ieeeAddress = ieeeAddress;
		this.validation = validation;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getCoordinatorId() {
		return this.coordinatorId;
	}

	public void setCoordinatorId(Integer coordinatorId) {
		this.coordinatorId = coordinatorId;
	}

	public String getIeeeAddress() {
		return this.ieeeAddress;
	}

	public void setIeeeAddress(String ieeeAddress) {
		this.ieeeAddress = ieeeAddress;
	}

	public Integer getValidation() {
		return this.validation;
	}

	public void setValidation(Integer validation) {
		this.validation = validation;
	}

}
